### ISSUE TITLE
Official docker image is missing ODBC libs

### ISSUE THREAD

**Issue by sgofferj** [limbas/limbas-docker#1]
I pulled the limbas/limbas:latest docker image and ran the installer at /admin/install
I entered the connection information to the mysql container

Connection is failing with:

Database connection failed
(Driver=MySQL;Server=ws-mariadb;Database=limbas;ReadOnly=No)
[unixODBC][Driver Manager]Can't open lib '/usr/lib64/libmyodbc5.so' : file not found

Database connection failed
(Driver=MySQL;Server=ws-mariadb;Database=limbas;ReadOnly=No)
[unixODBC][Driver Manager]Can't open lib '/usr/lib64/libmyodbc5.so' : file not found

libmyodbc5.so indeed is not present anywhere in the image.

**Comment by PeterGreth** [comment]
Hi! The limbas docker container is ready to be used with the PostgreSQL database. In order to use it with the MySQL database, you need to install the mysql odbc connector:
`docker exec -i <runningLimbasContainerName> yum install mysql-connector-odbc`

A docker version using pdo instead of odbc will be released soon!

**Comment by PeterGreth** [comment]
The new limbas docker version is now available on github/dockerhub

**Comment by sgofferj** [comment]
Jep, works :). Thanks for the fix!

**Comment by sgofferj** [comment]
Or not...
After completing the installation, I just get a white screen. The httpd access_log shows an error 500, the error_log shows nothing.

```192.168.10.1 - - [26/Sep/2019:16:46:28 +0000] "GET / HTTP/1.1" 500 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"```

**Comment by PeterGreth** [comment]
Can you give us more information? What commands did you use to start the containers? Which mysql image are you using?

**Comment by sgofferj** [comment]
Containers were deployed through the portainer orchestrator with no extra options. The mysql image is mariadb/mariadb:latest. I have one central mysql container for all webservices. The install went through without error messages and the Limbas database has been populated. The limbas db-user is db-specific, i.e. it has only access to the limbas database, nothing else.
I'd love to give more information but the container isn't logging awfully much :frowning_face:

**Comment by PeterGreth** [comment]
Unfortunately I cannot help you with portainer orchestrator. We got limbas/pdo/mysql running using docker-compose:
```
version: "2"
services:
  limbas:
    image: limbas/limbas:latest
    restart: always
    ports:
      - '8001:80'
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_DATABASE: 'limbasdb'
      MYSQL_USER: 'limbasuser'
      MYSQL_PASSWORD: 'limbaspw'
```

Connection works with "db" as host.
Hope that helps!
